### ISSUE TITLE
Run simulations for "Conservative marketplace"

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#110]
Conservative marketplace:
100% Rating coverage across transactions
5% “bad users” (including bot-net owners and bot-nets)
Transaction ratios good/bad agents of 1, 5, 10 
Transaction amount volume ratios for good/bad agents 1, 5, 10, 20
90% buyers + 10% sellers
Products on the market = 2
Price range ratio (most expensive/least expensive) = 2
-----------
1) run simulations for "most interesting" market type with "champion" settings for RS found or "Risky marketplace" - with and w/o RS (2X12 rows)
2) find "borderline conditions" (based on where we start improving LTS)
3) search parameters space around, starting with new option for "domain-specific reputations normalisation" (some more rows with fixed market type and conditions) and find new "champion" set of parameters (or confirm the earlier one) 
4) for found (possibly new) "champion" parameters, run simulation for implicit financial ratings AND explicit ratings with weighting=False (2 runs) 
5) for found "champion" parameters, run simulation with and without of "aggregation" using Python RS

**Comment by akolonin** [comment]
Tracking here: https://docs.google.com/spreadsheets/d/1lNrbDUT2L_lqpn_-jwIBrWSCiHp6SJoBSkYUSPNuJx0/edit#gid=2080603677

**Comment by deborahduong** [comment]
https://docs.google.com/spreadsheets/d/1SDbgn-aTg2c2l2QHM0V_b8Ert-ieKiS4jjaZulsVWqM/edit#gid=1414051887

**Comment by deborahduong** [comment]
The above link includes the downrating denom log and norm parameter sweeps for the values of decay conserv and default all set to 0.5 in a conservative market. It includes 3 separate runs of the norep, but more are needed as there is a high variance.  This issue was paused at 3 to make the simulation realistic in other ways.  done on the milk and honey scenario, on codes around MVR 50 ((multiple codes rather than a single code because of high variance )  run on ratings, AR TR codes of : ['r_10_1','r_5_1','r_1_1','r_10_0.5','r_5_0.5','r_20_0.1','r_10_0.1','r_5_0.1']

**Comment by deborahduong** [comment]
jupyter notebook :  reputation_results-conserv denom log norm
