### ISSUE TITLE
Run the champion parameters around 30 times 

### ISSUE THREAD

**Issue by deborahduong** [singnet/reputation#116]
Time should be left before submission of the publication to run the two champion run multiple times, depending on the variance of the output, but we should make time for running about 30 times  This is necessary because our simulation is stochastic and the simulation community standard is to have multiple runs before conclusions are drawn.  (We were able to draw conclusions privately because we actually have run these more than 30 times, without the exact parameters, so we know how it behaves in general- but for form the last version, hopefully under a code freeze and with the winning set, needs be run multiple times,  and significance reported.   This one depends on the nohup debugging being complete, because that long a batch job is bound to have network interruptions.  For Debbie

**Comment by akolonin** [comment]
If there is concern like that, I would rather sooner take 3 configurations of 10, 20, 100 with "champion" set or parameters and run them 3 times to see if the results are repeatable. Because if there results are not repeatable, entire analysis makes no any sense, not only the "champion"
BTW, the "champion" should be defined based on LTS metric, as suggested by Cassio.
