### ISSUE TITLE
Simulating advanced scam campaigns (Amazon case)

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#214]
@pennachin wrote:
Reading the article linked, it shouldn’t be too difficult to create a set of parameters for the reputation system that mimics the marketplace view of such a scam. You’d have dedicated scam sellers (we already have that) and mixed behavior buyers (which rate good sellers honestly; rate _some_ bad sellers honestly; rate _specific_ bad sellers very highly). We don’t have those buyers (IIRC) but @nejc already pointed out we need them. We’d need some externally imposed connection between the scam sellers and these new buyers. And we’d probably need continuous campaigns, but in which the scam buyers rate sellers with the same frequency as other buyers so as not to look suspicious.
https://thehustle.co/amazon-fake-reviews

**Comment by nejc9921** [comment]
Current work on modeling scam campaigns (for sellers, it is already done):
https://docs.google.com/document/d/1EkRslOtZvQKeCdDmwLRGkcye8QEehtr09NgiBa2CbEU/edit

**Comment by akolonin** [comment]
@nejc9921 , the analysis above is done based on Amazon context with written "reviews". In such model, I would expect fewer fake reviews and fewer fake reviewers. In SNET marketplace ratings  design suggested by @pennachin we rather have "thumbs-up" and "thumbs-down" ratings which could effect in much more fake reviews and more fake reviewers because this kind of rating seems to be much cheaper per unit. This is the difference between making a "like" or "vote" in social network as opposed to writing a "comment". Do you think your model will be still good for that?

**Comment by deborahduong** [comment]
The game in which the Amazon scammers are playing is based on paying for a review by sending free merchandise and a commission, all because to have "verified" review , you have to have a physical address that the merchandise was sent to.  Snet can verify without that physical address so it would not be worth it to pay a human a rating. Much cheaper to have your own address buy it.  But more importantly, the feedbacks would not be represented properly if we were to take the advice of the paper and calculate the number of scams exogenously to the system. The parameters mentioned depend upon the reputation system.  For example, the number of purchases required to either get a good rating or to catch a bad guy.  To test the system , we have to have the bad agents react only to the reputation system.  which isn't hard to do at all. However, Nejc's equations are good for simulating the decision of a person to cheat at all.  While it is not clear that the opportunity cost of the cheater is being honest (because he may not have the skills to be honest, whether it is make good AI software or quality phone screens) , Nejc's ideas are getting at an important point in Cassio's article - that in some states of a system which uses a reputation system in a winner take all fashion, people have to cheat to stay in the game at all.  That is something we definitely want to avoid.  However, I think it is best modelled in my Equity project:  where I would look at a wrapper to use the reputation system , and how this affects the equity in the system.  It would look at feedback, that kind that makes a corrupt society so that you have to be corrupt just to play.  (I actually have modelled the say societies switch to corrupt states in an intelligent agent system with feedback professionally before).

**Comment by pennachin** [comment]
@akolonin The fake reviews are from people being financially incentivized to post them. So I don't think the effort makes a huge difference.

**Comment by akolonin** [comment]
@pennachin - why do I need to pay people to post the ratings? I would rather create as many bots as I alike the the bots make the ratings or I just subcontract to the bot hosting business so they run a farm of rating-posting bots for me. If we are in AI era and on AI market, that would be the same even for reviews - assuming bots are trained or given templates for review writing. I think it would be a bit different economy than paying individuals per review.

**Comment by pennachin** [comment]
The Amazon studies are specifically about real people being paid (or otherwise compensated) to sometimes act as scammers. This is the goal here. Detecting bots is much easier and lower value than detecting real users who are sometimes legit and sometimes not.

**Comment by nejc9921** [comment]
In my system, only some people would scam and would look for them to be profitable to scam. Not everyone is willing to risk its known reputation to scam people because if you get caught scamming there can be potential consequences that are worse than just us banning their ID online - for big businesses that can mean that consumers might have decreased trust in their services. So, it is not assumed everyone will cheat.

As for paying people for ratings vs making a bot: Paying people will give you an edge over the bots since they might have accounts that react more natural, thus might have better history. This matters sometimes in our simulations, depending on the parameters we choose.
Bots tend to behave in certain order and they can sometimes get detected by reputation police. In fact, I would bet Amazon catches a lot of bots - I imagine they have some algorithms that flags the product that got 1000 5-star reviews in a day all from newly created accounts (and I believe they also say they do). Not saying cheating with bots is impossible, but if you want quality cheating, it is probably better to do it manually. And that costs money.

**Comment by deborahduong** [comment]
My main concern is having this static number of scam purchases, when the relation between how many purchases it takes to make it worth it through sales is ever changing and depends on both the reputation system and the competition. We do not what the situation where we have a static number of scam purchases, making it so that the scam agents pull out when their reputation score is rising, and had they stayed  a little longer, they would make their profit.

**Comment by nejc9921** [comment]
In the document I proposed so far I believe that this is actually a number that will change for different products... It depends on how much profit they expect to make.

I am working on similar issues now, the first thing that I set myself to do is to actually study again how many reviews are posted by fake buyers (before 40% of them had only 1 review, while the real users had this percentage at 20. However, I found some methodology issues with it).

**Comment by deborahduong** [comment]
By static, I mean static per product vs. in reaction to the reputation system, online

**Comment by nejc9921** [comment]
In this case, "purch" variable (expected purchases) could be changing for each time they make a new campaign - they have better knowledge how much they can expect. For example: the first time they will make a guess how many sales they will get and then, when considering the next campaign, their guess will be more educated based on how much they sold since their last campaign.

**Comment by deborahduong** [comment]
That's better, but still, they wouldn't pull out when their situation is quickly improving, regardless of the past

**Comment by nejc9921** [comment]
yeah, that would need some thinking.

**Comment by deborahduong** [comment]
Well, I agree with your equations, but in a way they are the reflections of utility seeking behavior.  They are good for planning - for example, the decision of otherwise honest agents to cheat just to make a living - but they would come out of utility seeking behavior.

**Comment by deborahduong** [comment]
If detecting bots is easy (and I have a feeling that they are adapting so that its not so easy) then shouldn't our reputation system do at least that?

**Comment by nejc9921** [comment]
> They are good for planning - for example, the decision of otherwise honest agents to cheat just to make a living - but they would come out of utility seeking behavior.

Well, I meant it more for those that are already fraudulent to decide how much they want to put into the fraud. Honest agent might have a profit from fraud, but might not follow the equations I set - simply because it's honest. After all, what they are doing is bad for their image, possibly borderline illegal if not illegal and not everyone might do it, even if it brings them profit.

> An observer would note that an agent seeking utility would behave that way after the fact, but that doesnt mean that the agent has to have that equation to seek utility.

As mentioned, this is meant only for those that are scammers. Honest agents might not want to follow such utility seeking, since there is some kind of boundry if we can call it that way to enter - that would be moral boundry or something like that.

**Comment by nejc9921** [comment]
> If detecting bots is easy (and I have a feeling that they are adapting so that its not so easy) then shouldn't our reputation system do at least that?

From what I understand catching bots is cat and mouse game. We develop an algo (reputation police) that will catch certain type of behavior and then they adapt, then we release new algo. Possibly our algorithm might even update itself with new feats, if needed and if constructed properly. I don't think we can possibly catch all bots, but some can be caught. And that makes it harder to make an effective bot that will evade police and thus more expensive.

**Comment by deborahduong** [comment]
Hi - by utility seeking, I meant utility seeking of bad agents.  IOW, a bad agent would react to the now, the profit or expected increase of profit now, and behavior like this, would fit your equation after the fact.

**Comment by nejc9921** [comment]
Not sure if I understand what you mean - so the problem is that bad agents do not react on changes in real time, but rather wait until they are done with their campaign and only then stop, even though they might have achieved their goal before they are done faking reviews?

**Comment by deborahduong** [comment]
I think realistically bad agents would continue to purchase scam ratings as long as it increased their profits and stopped if it decreased their profits, and they can monitor this online, just by observing if their pocket book is growing or shrinking, or if their reputation score is changing in such a way as to make them believe the pocketbook will soon grow or shrink .    The thing is, they wouldn't have a static goal, they would want to maintain a rating, dynamically, by adding more scam purchases to get it up as long as they see money coming in, continually adjusting the amount online in response to profit.
  But yes, they could possibly purchase too many scams, however you would measure this by their not making money online.  and they could possibly purchase too few as well, as you could see with a rapidly increasing score that wasn't maintained.

**Comment by deborahduong** [comment]
The anticipation component, of "Will I soon have profit given my rating change?" , is one thing to be learned.  but I would venture to say that in the absence of any penalty of getting caught , if they are actually making a profit they would stay.

**Comment by pennachin** [comment]
While there is lots of good thought here, I want to remind us that the point of this particular issue is to simulate scam campaigns of the nature reported in the original issue definition and covered in @nejc9921's report. So one step at a time, focus, etc.

**Comment by nejc9921** [comment]
I believe Deborah is pointing out the flaws of that report, which is on topic in my opinion. Or is it not?
Original post (by Anton):

> And we’d probably need continuous campaigns, but in which the scam buyers rate sellers with the same frequency as other buyers so as not to look suspicious.


So, I believe @deborahduong is pointing out the lack of continuos campaigning, though I am thinking that perhaps I could somehow include some frequency parameter. So, the discrete campaigns currently implemented would become shorter and then this continuos effect can be minimized. Given that parameters can be adjusted, this can be done currently maybe by joining shorter scam active period and potentially more scam periods - but perhaps better would be if I would find a way to somehow add things to the mix in order to get this continuousness (not sure if this would be correct word for what we are looking for). I can work on that.

Another thing why the system is currently the way it is is that in scammer's perspective, if they get more fake ratings, then perhaps the reputation will hold on to their product for longer. So, they might ignore immediate effect, but it's true that this is not necessarily realistic.

**Comment by deborahduong** [comment]
I would think that the thing that would end a campaign would be the reputation system giving the bad agent rings lower scores than they would have if they stopped and came back under new aliases.  So it would be in direct reaction to a decrease in profit, and indirectly to the reputation score.  The scam agents perception of the relation between the reputation system rating  and earnings - such as you point out , of holding on to the product for longer - can be learned

**Comment by nejc9921** [comment]
Perhaps we can just add a certain stoppage criteria inside the scam campaigns that the campaign is stopped as soon as their rating is below a certain treshold? I would say that agents somehow have an idea about their rating; they can track where are their search results are displayed and if they see no improvements that might discourage them.

Though, if you'd be trying to boost your ranks on Google, you could also expect Google to initially freeze you as you are a new agent there. This is why such a thing might not discourage the bad agents as they might suspect that they are in freezout phase.

**Comment by pennachin** [comment]
I believe continuous campaigns aren't strictly needed in the first round of experiments. It's easy to see how they could be added on top of the initial design.

**Comment by akolonin** [comment]
I think - given the goal posed by @pennachin with the referenced publication we should not have "campaigns" in the sense of our earlier simulations - because the "fake charger vendor" will stay the same for long time - during entire simulation. However, the generations of the "fake consumers" will definitely have to refresh so it does not look suspicious for the Amazon's "fake reviews police". But I don't think this should be matter of "generations" at all, we will gust have to simulate (@deborahduong ) population of dishonest reviewers making many fake reviews (1 per vendor) with high ratings to the products that get rather negative reviews from the honest reviewers. On the "catch them all" project, that might be more "network analysis" kind of task and if we solve that, we can rethink it in terms of reputation system parameters on the next step.

**Comment by akolonin** [comment]
Agreed:
- @deborahduong + to update the spec for Amazon Case of simulation to based on model provided by @nejc9921 
- @nejc9921 - study Amazon data for averages and variances of relationships vendor<=>product, product<=>rater/buyer, vendor<=>rater/buyer with account to different product categories ad probability of rating to be fake

**Comment by pennachin** [comment]
My understanding is that those vendors engage very explicitly in campaigns, so I don't understand why you want to remove them. The difference is they focus on campaigns for specific products (usually new ones) but we don't need to explicitly model that in the first round of simulations...

> we should not have "campaigns" in the sense of our earlier simulations - because the "fake charger vendor" will stay the same for long time

**Comment by akolonin** [comment]
According to https://docs.google.com/document/d/1-O7avb_zJKvCXRvD0FmvyoVZdSmkDMlXRB5wsavpSAM/edit#
Simulation setups:
A) No reputations system
B) "Regular" reputation system
C) Weighted+TOM+SOM
D) Denominate ratings by average ratings of the same rater in the past
E) Weight ratings by predictive power of the raters
F) Denominate ratings based on “anomalyous over-consumption” patterns of the raters in specific product categories

**Comment by akolonin** [comment]
Remaining TODOs:
1) Add assessment of RS=Predictive, with 'predictiveness'=1.0 using latest Java RS
2) Check why/if Weighted works better than Biased
3) Check why increase of PLRo makes financial metrics worse (with "Regular" RS)
4) Explore how the competition CR effects on the metrics (with "Regular" RS)
5) Denominate ratings based on “anomalous over-consumption” patterns of the raters in specific product categories

**Comment by akolonin** [comment]
Need the same sheet as I have here https://docs.google.com/spreadsheets/d/1Dm5u_YuT-MYhSY0XkfZ2dZ7CqHv2exSWc4VQYnm7NWM/edit#gid=1031307589 with the same lines and coloring, with the only differences:
1) Maybe more columns like SGL and SGP but don't include columns that make no sense or don't change at all like no-ever-changing equity
2) Different numbers, of course
3) Maybe few more PLRo lines for "RS=Regular" if you want to be more detailed at 5%, 10%, 15%
4) Maybe different "borderline" PLRo for RS experiments, like if you find 15% or 10% is more reasonable (30% by default)
5) Don't include smaller than 1000 populations, if you don't have time for them, we can play with populations later
6) Add evaluation of "RS=Parents" with settings: rs.set_parameters({'parents':1.0,'predictiveness':0.0,'rating_bias':False,'fullnorm':True,'weighting':True ,'logratings':False,'denomination':True ,'unrated':False,'default':0.5,'decayed':0.5,'ratings':1.0,'spendings':0.0})

**Comment by akolonin** [comment]
At this point, there are few remaining work items:
1) Summarise the best configurations of of parameters for every type of "winning" reputation system 
2) Explore all possible blending options of the different types of reputation systems and the best parameters for the blendings (may end up with the need for separate "predictiveness conservatism" parameter)  
3) Extend the model for "much more than 1 product in each price category"
4) Explore why OMU metric is not working and either find how to make it working or explain why it should not work

**Comment by deborahduong** [comment]
I think there is a misunderstanding:  we don't have one product in each price category.  we have a bad supplier selling one product category, which also is in one price category.  It has an average of 100 products within the product category.  Discussion about this and "enterers and leavers" is in a comment on the business analysis document

**Comment by akolonin** [comment]
For the record: "The relative ranks of the agents in the reputation system are what is important, because sellers that are higher on the chart are more recommended by the reputation system than agents that lower on the chart." makes no sense to me as well no variance of the OMU in the "adaptive simulation" because 5-stars mean 0.75-1.0 interval and 0.5-0.75 is 4-stars interval, so the above can be true only if you recommend to buy from any number of stars if that is above the  average number of stars. But let's dicuss this after finishing the current report.

**Comment by deborahduong** [comment]
Concerning the lower red and blue dots on the bias chart vs regular chart:I just checked and the reason that all scores are generally lower in the biased run is that the champion decayed parameter is 1.  In runs with decayed=9, they are as high as they are on the regular run

**Comment by deborahduong** [comment]
Concerning OMU, in my simulation, good2bad, in the denominator added to good2good, is small compared to good2good because of the other 4 product categories present in the simulation, which have their own separate market volume that forms the bulk of the market volume in the economy.   That is why ~good2good/(good2bad+good2good)  is close to 1

**Comment by akolonin** [comment]
The legend continues in #264
